accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    re_path(r'by/(?P<username>[-\w]+)',
            views.UserPosts.as_view(), name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',
            views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rant</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://bootswatch.com/4/lumen/bootstrap.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Google font (Roboto) -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

</head>

<body>

    <nav class='navbar navbar-expand-lg navbar-light bg-light' style="margin-bottom: 50px" role='navigation', id='navbar'>
        <div class='container'>
            <a class="navbar-brand" href="{% url 'home' %}">Rant</a>

            <ul class='nav justify-content-end'>
                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'posts:create' %}">Post</a></li>
                    <li><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>

        </div>

    </nav>

    <div class="container mycontent">
        {% block content %}
    
        {% endblock  %}
    </div>


</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Welcome to Rant!</h1>
        <h4>The only place to complain about anything and everything.</h4>
    </div>
{% endblock  %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
    <h1>You are now logged in!</h1>

{% endblock  %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>

{% endblock  %}